# --- 模型权重 ---
# 这是你之前下载好的 Facebook MAE 预训练权重
# mae_ckpt: "checkpoints/mae_pretrain_vit_base.pth" #initial
mae_ckpt: "/mnt/c/Users/81493/OneDrive/Desktop/runs/mae_decoder/best.pth"

# --- 数据配置 ---
data:
  # 训练数据的文件夹 (刚才生成的)
  # data_root: "data_preprocessed"#original
  data_root: "/home/tinger/data_fast" #modified
  
  # 模型输入尺寸 (虽然数据是112，但MAE需要224，代码会自动放大)
  out_size: 224
  
  # 使用多模态模式
  channel_mode: "modalities"
  # 对应 preprocess_isles.py 里保存的键名
  modality_keys: ["dwi", "adc", "flair"]
  mask_key: "mask"
  
  # 验证集比例 (20%用来测试)
  val_frac: 0.2
  
  # 归一化 (非常重要)
  normalize: True

# --- 训练参数 ---
train:
  epochs: 50             # 训练 50 轮
  batch_size: 16         # 如果显存不够报错(OOM)，可以改小成 8 或 4
  num_workers: 4         # 加载数据的线程数
  amp: True              # 开启混合精度训练 (省显存，速度快)

# --- 优化器 ---
optim:
  lr: 1e-3               # 学习率
  wd: 0.05               # 权重衰减

# --- 损失函数 ---
loss:
  focal_w: 0.5           # Focal Loss 权重 (关注难分类样本)
  dice_w: 0.5            # Dice Loss 权重 (关注分割形状)

# --- 评估指标 ---
metrics:
  dice_thr: 0.5
  roc:
    enabled: True        # 开启你需要的 ROC/AUC 曲线
    save_plot: True      # 训练时自动保存 AUC 图片
