data:
  root: "../ISLES-2022-npz-multimodal_clean/all"
  train_list: "../ISLES-2022-npz-multimodal_clean/splits/train.txt"
  val_list: "../ISLES-2022-npz-multimodal_clean/splits/val.txt"
  img_size: 224

model:
  hidden_dims: [128]
  dropout: 0.0

train:
  batch_size: 32
  val_batch_size: 32
  epochs: 40
  lr: 1.0e-4
  weight_decay: 1.0e-4
  num_workers: 8
  pin_memory: true
  output_dir: "../runs/mlp_slice_classifier"
